1Q)What is the total revenue generated by male vs female customers?
SELECT gender,Sum(purchase_amount) as revenue
 FROM final_shopping_data 
 group by gender;
 2)which customers used a discount but still spent more than the average purchase amount?
 select customer_id,purchase_amount
 from final_shopping_data
 where discount_applied='Yes' and purchase_amount>= (select AVG(purchase_amount) from final_shopping_data)
 
 3)which are the top 5 products with the highest average review rating?
 select item_purchased,round(avg(review_rating),2) as "average product rating"
 from final_shopping_data
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;
 
 4)compare the avg purchase amounts between standard and express shipping?
 select shipping_type,
 round(avg(purchase_amount),2)
 from final_shopping_data
 where shipping_type in ('standard','express')
 group by shipping_type
 
 5)Do subscribed customers spend more?compare avg spend and total revenue between subscribers and non subscribers?
  select subscription_status,
  count(customer_id) as total_customers,
  round(avg(purchase_amount),2)as avg_spend,
  round(SUM(purchase_amount),2) as total_revenue 
  from final_shopping_data
  group by subscription_status
  order by total_revenue,avg_spend desc;
  
  6)which 5 products have the highest percentage of purchases with discounts applied?
  select item_purchased,
  round(sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*)*100,2) as discount_rate
  from final_shopping_data
  group by item_purchased
  order by discount_rate desc
  limit 5;
  
  7)segment customers into new,returningand loyal based on their total number of previous purchases and show the count of each segment?
   with customer_type as(
   select customer_id,previous_purchases,
   case
	when previous_purchases=1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
  from final_shopping_data
  )
  
select customer_segment,count(*) as 'number of customers'
from customer_type 
group by customer_segment

8)what are the top 3 most purchased products within each category?
  with item_counts as (
  select category,
  item_purchased,
  count(customer_id) as total_orders
  from final_shopping_data
  group by category,item_purchased
  )
  select *
  from(
  select
  category,
  item_purchased, 
  total_orders,
  row_number() over(partition by category order by total_orders desc
  ) as item_rank
  from item_counts
  ) t
  where item_rank<=3;  
  
  9)are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
  select subscription_status,
  count(customer_id) as repeat_buyers
  from final_shopping_data
  where previous_purchases>5
  group by subscription_status
  
  10)what is the revenue contribution of each age group?
  select age_group,
  sum(purchase_amount) as total_revenue
  from final_shopping_data
  group by age_group
  order by total_revenue desc;